//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC_AVO_DEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public long Id { get; set; }
        public long IdHistorial { get; set; }
        public string NombreUsuario { get; set; }
        public byte[] Password { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Apellido { get; set; }
        public string Rut { get; set; }
        public long IdRol { get; set; }
        public long IdRolHistorial { get; set; }
        public int IdEmpresa { get; set; }
        public int IdEmpresaHistorial { get; set; }
        public string Observaciones { get; set; }
        public string Direccion { get; set; }
        public string URLFoto { get; set; }
        public string PersonaContactoEmergencia { get; set; }
        public string TelefonoContactoEmergencia { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public long IdUsuarioCreador { get; set; }
        public Nullable<long> IdUsuarioCreadorHistorial { get; set; }
        public int IdDepartamento { get; set; }
        public int IdDepartamentoCargo { get; set; }
        public long IdDepartamentoCargoHistorial { get; set; }
        public Nullable<int> VigenciaPassword { get; set; }
        public Nullable<int> AvisoCambioPassword { get; set; }
        public Nullable<System.DateTime> FechaAviso { get; set; }
    }
}
